//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Management.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Calendar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Calendar() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Management.Properties.Calendar", typeof(Calendar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   金 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Week_Friday {
            get {
                return ResourceManager.GetString("Week_Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   月 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Week_Monday {
            get {
                return ResourceManager.GetString("Week_Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   土 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Week_Saturday {
            get {
                return ResourceManager.GetString("Week_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Week_Sunday {
            get {
                return ResourceManager.GetString("Week_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   木 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Week_Thursday {
            get {
                return ResourceManager.GetString("Week_Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   火 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Week_Tuesday {
            get {
                return ResourceManager.GetString("Week_Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   水 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Week_Wednesday {
            get {
                return ResourceManager.GetString("Week_Wednesday", resourceCulture);
            }
        }
    }
}
