//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Management.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ClientInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClientInfo() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Management.Properties.ClientInfo", typeof(ClientInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   住所 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   口座 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BankAccount {
            get {
                return ResourceManager.GetString("BankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取引先一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClientList {
            get {
                return ResourceManager.GetString("ClientList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   会社名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メールアドレス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EMailAddress {
            get {
                return ResourceManager.GetString("EMailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集中のデータを反映せずに終了しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageClose {
            get {
                return ResourceManager.GetString("MessageClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   「*」を新たに取引先一覧に登録しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageListAdd {
            get {
                return ResourceManager.GetString("MessageListAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   「*」を取引先一覧より削除しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageListRemove {
            get {
                return ResourceManager.GetString("MessageListRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageSave {
            get {
                return ResourceManager.GetString("MessageSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   「*」を新たに担当一覧に登録しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageStaffAdd {
            get {
                return ResourceManager.GetString("MessageStaffAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   「*」を担当一覧より削除しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MessageStaffRemove {
            get {
                return ResourceManager.GetString("MessageStaffRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   連絡先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MobilePhone {
            get {
                return ResourceManager.GetString("MobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TEL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PhoneNo {
            get {
                return ResourceManager.GetString("PhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   振り仮名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Phonetic {
            get {
                return ResourceManager.GetString("Phonetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   氏名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StaffName {
            get {
                return ResourceManager.GetString("StaffName", resourceCulture);
            }
        }
    }
}
