//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Management.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JobList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JobList() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Management.Properties.JobList", typeof(JobList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   取引先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   封筒・送付状 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CoverLetterFile {
            get {
                return ResourceManager.GetString("CoverLetterFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作成日時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateDateTime {
            get {
                return ResourceManager.GetString("CreateDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納品書 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeliveryFile {
            get {
                return ResourceManager.GetString("DeliveryFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納期 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeliveryInfo {
            get {
                return ResourceManager.GetString("DeliveryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   詳細 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作成済 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileExist {
            get {
                return ResourceManager.GetString("FileExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileNoExist {
            get {
                return ResourceManager.GetString("FileNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   請求書 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvoiceFile {
            get {
                return ResourceManager.GetString("InvoiceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名称 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   金額 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   見積書 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string QuotationFile {
            get {
                return ResourceManager.GetString("QuotationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   改訂 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Revision {
            get {
                return ResourceManager.GetString("Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ステータス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納品 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Status_Delivery {
            get {
                return ResourceManager.GetString("Status_Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Status_Finished {
            get {
                return ResourceManager.GetString("Status_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   - に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Status_None {
            get {
                return ResourceManager.GetString("Status_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未注 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Status_NotOrdered {
            get {
                return ResourceManager.GetString("Status_NotOrdered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   受注 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Status_Ordered {
            get {
                return ResourceManager.GetString("Status_Ordered", resourceCulture);
            }
        }
    }
}
