//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Management.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Quotation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Quotation() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Management.Properties.Quotation", typeof(Quotation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   正式受注後 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AfterReceiptOfOrder {
            get {
                return ResourceManager.GetString("AfterReceiptOfOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   御中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ご担当： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ClientStaffName {
            get {
                return ResourceManager.GetString("ClientStaffName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *日間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納期： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeliveryDate {
            get {
                return ResourceManager.GetString("DeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E-Mail： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EMail {
            get {
                return ResourceManager.GetString("EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   （税抜） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExcludingTax {
            get {
                return ResourceManager.GetString("ExcludingTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   有効期限： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExpirationDate {
            get {
                return ResourceManager.GetString("ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   御見積後2週間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExpirationDateMessage {
            get {
                return ResourceManager.GetString("ExpirationDateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   お振込手数料は御社ご負担にてお願い致します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FixedPhrase1 {
            get {
                return ResourceManager.GetString("FixedPhrase1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納期の入力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InputDeliveryDate {
            get {
                return ResourceManager.GetString("InputDeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   件名： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   担当： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MasterName {
            get {
                return ResourceManager.GetString("MasterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   下記のとおり、御見積もり申し上げます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *ヶ月間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Page に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   支払条件： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PaymentTerms {
            get {
                return ResourceManager.GetString("PaymentTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   月末締め翌月末払い に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PaymentTermsMessage {
            get {
                return ResourceManager.GetString("PaymentTermsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   個 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Pieces {
            get {
                return ResourceManager.GetString("Pieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   金額 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   見積日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string QuotationDate {
            get {
                return ResourceManager.GetString("QuotationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   見積No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string QuotationNo {
            get {
                return ResourceManager.GetString("QuotationNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   備考 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   客先担当の選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectedClientStaffs {
            get {
                return ResourceManager.GetString("SelectedClientStaffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   式 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sets {
            get {
                return ResourceManager.GetString("Sets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   小計 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SubTotal {
            get {
                return ResourceManager.GetString("SubTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   摘要 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TEL： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   御　見　積　書 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   合計金額 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   単価 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   台 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数量 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *週間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Weeks {
            get {
                return ResourceManager.GetString("Weeks", resourceCulture);
            }
        }
    }
}
