//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Management.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Title {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Title() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Management.Properties.Title", typeof(Title).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   カレンダー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取引先登録 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClientAdd {
            get {
                return ResourceManager.GetString("ClientAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取引先情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClientInfo {
            get {
                return ResourceManager.GetString("ClientInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   担当者登録 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ClientStaffAdd {
            get {
                return ResourceManager.GetString("ClientStaffAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納期入力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InputDeliveryDate {
            get {
                return ResourceManager.GetString("InputDeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ジョブ詳細 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JobDetail {
            get {
                return ResourceManager.GetString("JobDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ジョブ一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JobList {
            get {
                return ResourceManager.GetString("JobList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ジョブ管理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マスタ情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MasterInfo {
            get {
                return ResourceManager.GetString("MasterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   御見積書 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Quotation {
            get {
                return ResourceManager.GetString("Quotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取引先担当選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectedStaff {
            get {
                return ResourceManager.GetString("SelectedStaff", resourceCulture);
            }
        }
    }
}
